# Generated by Django 3.2.6 on 2021-08-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('overview', models.TextField(blank=True, null=True)),
                ('structure_one', models.TextField(blank=True, null=True)),
                ('structure_two', models.TextField(blank=True, null=True)),
                ('structure_three', models.TextField(blank=True, null=True)),
                ('structure_four', models.TextField(blank=True, null=True)),
                ('structure_five', models.TextField(blank=True, null=True)),
                ('example_one', models.TextField(blank=True, null=True)),
                ('example_two', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
