# Generated by Django 3.2.6 on 2021-08-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure_gen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stories',
            new_name='Story',
        ),
    ]
