# Generated by Django 3.2.6 on 2021-08-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure_gen', '0002_rename_stories_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
    ]
